
# This file is automatically generated, you probably don't want to edit this

LMGCEOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "LMGCEOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            run = FALSE,
            dep = NULL,
            covs = NULL,
            factors = NULL,
            intercept = TRUE,
            caseGLM = "D",
            supportMethod = "standardized",
            ridgeSignalSupport = "symm",
            ridgeLambdaMin = 0.001,
            ridgeLambdaMax = 1000,
            ridgeLambdaN = 100,
            M = 3,
            J = 3,
            weight = 0.5,
            cvNfolds = 5,
            errorMeasure = "RMSE",
            errorMeasureWhich = "1se",
            supportSignalVectorMin = 0.3,
            supportSignalVectorMax = 20,
            supportSignalVectorN = 20,
            noiseSupportMethod = "sigma3",
            twostepsN = 1,
            seed = 230676,
            OLS = FALSE,
            NormEnt = FALSE,
            bootstrap = FALSE,
            bootB = 10,
            bootMethod = "residuals",
            bootCIMethod = "percentile",
            bootConfLevel = 0.95,
            method = "dual.BFGS",
            plot1 = TRUE,
            plot2 = TRUE,
            plot3 = TRUE,
            plot4 = FALSE,
            plot5 = FALSE,
            plot6 = FALSE,
            plot7 = FALSE,
            plotRidge = FALSE,
            trueCoef = "", ...) {

            super$initialize(
                package="GCEstimjmv",
                name="LMGCE",
                requiresData=TRUE,
                ...)

            private$..run <- jmvcore::OptionAction$new(
                "run",
                run)
            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs)
            private$..factors <- jmvcore::OptionVariables$new(
                "factors",
                factors)
            private$..intercept <- jmvcore::OptionBool$new(
                "intercept",
                intercept,
                default=TRUE)
            private$..caseGLM <- jmvcore::OptionList$new(
                "caseGLM",
                caseGLM,
                options=list(
                    "D",
                    "M",
                    "NM"),
                default="D")
            private$..supportMethod <- jmvcore::OptionList$new(
                "supportMethod",
                supportMethod,
                options=list(
                    "standardized",
                    "ridge"),
                default="standardized")
            private$..ridgeSignalSupport <- jmvcore::OptionList$new(
                "ridgeSignalSupport",
                ridgeSignalSupport,
                options=list(
                    "symm",
                    "asymm"),
                default="symm")
            private$..ridgeLambdaMin <- jmvcore::OptionNumber$new(
                "ridgeLambdaMin",
                ridgeLambdaMin,
                default=0.001,
                min=1e-12)
            private$..ridgeLambdaMax <- jmvcore::OptionNumber$new(
                "ridgeLambdaMax",
                ridgeLambdaMax,
                default=1000,
                min=1e-12)
            private$..ridgeLambdaN <- jmvcore::OptionInteger$new(
                "ridgeLambdaN",
                ridgeLambdaN,
                default=100,
                min=2)
            private$..M <- jmvcore::OptionInteger$new(
                "M",
                M,
                default=3,
                min=3,
                max=99)
            private$..J <- jmvcore::OptionInteger$new(
                "J",
                J,
                default=3,
                min=3,
                max=99)
            private$..weight <- jmvcore::OptionNumber$new(
                "weight",
                weight,
                default=0.5,
                min=0,
                max=1)
            private$..cvNfolds <- jmvcore::OptionInteger$new(
                "cvNfolds",
                cvNfolds,
                default=5,
                min=2)
            private$..errorMeasure <- jmvcore::OptionList$new(
                "errorMeasure",
                errorMeasure,
                options=list(
                    "RMSE",
                    "MSE",
                    "MAE",
                    "MAPE",
                    "sMAPE",
                    "MASE"),
                default="RMSE")
            private$..errorMeasureWhich <- jmvcore::OptionList$new(
                "errorMeasureWhich",
                errorMeasureWhich,
                options=list(
                    "1se",
                    "min"),
                default="1se")
            private$..supportSignalVectorMin <- jmvcore::OptionNumber$new(
                "supportSignalVectorMin",
                supportSignalVectorMin,
                default=0.3,
                min=0.01)
            private$..supportSignalVectorMax <- jmvcore::OptionNumber$new(
                "supportSignalVectorMax",
                supportSignalVectorMax,
                default=20,
                min=0.01)
            private$..supportSignalVectorN <- jmvcore::OptionInteger$new(
                "supportSignalVectorN",
                supportSignalVectorN,
                default=20,
                min=2)
            private$..noiseSupportMethod <- jmvcore::OptionList$new(
                "noiseSupportMethod",
                noiseSupportMethod,
                options=list(
                    "sigma3",
                    "maxres"),
                default="sigma3")
            private$..twostepsN <- jmvcore::OptionInteger$new(
                "twostepsN",
                twostepsN,
                default=1,
                min=0)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                default=230676,
                min=1)
            private$..OLS <- jmvcore::OptionBool$new(
                "OLS",
                OLS,
                default=FALSE)
            private$..NormEnt <- jmvcore::OptionBool$new(
                "NormEnt",
                NormEnt,
                default=FALSE)
            private$..bootstrap <- jmvcore::OptionBool$new(
                "bootstrap",
                bootstrap,
                default=FALSE)
            private$..bootB <- jmvcore::OptionInteger$new(
                "bootB",
                bootB,
                default=10)
            private$..bootMethod <- jmvcore::OptionList$new(
                "bootMethod",
                bootMethod,
                options=list(
                    "residuals",
                    "cases",
                    "wild"),
                default="residuals")
            private$..bootCIMethod <- jmvcore::OptionList$new(
                "bootCIMethod",
                bootCIMethod,
                options=list(
                    "percentile",
                    "basic"),
                default="percentile")
            private$..bootConfLevel <- jmvcore::OptionNumber$new(
                "bootConfLevel",
                bootConfLevel,
                default=0.95,
                min=0.5,
                max=0.99)
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "dual.BFGS",
                    "dual.lbfgsb3c",
                    "dual.L-BFGS-B",
                    "dual.lbfgs",
                    "dual.CG",
                    "dual.Rcgmin",
                    "dual.bobyqa",
                    "dual.newuoa",
                    "dual.nlminb",
                    "dual.nlm",
                    "primal.solnl",
                    "primal.solnp"),
                default="dual.BFGS")
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=TRUE)
            private$..plot2 <- jmvcore::OptionBool$new(
                "plot2",
                plot2,
                default=TRUE)
            private$..plot3 <- jmvcore::OptionBool$new(
                "plot3",
                plot3,
                default=TRUE)
            private$..plot4 <- jmvcore::OptionBool$new(
                "plot4",
                plot4,
                default=FALSE)
            private$..plot5 <- jmvcore::OptionBool$new(
                "plot5",
                plot5,
                default=FALSE)
            private$..plot6 <- jmvcore::OptionBool$new(
                "plot6",
                plot6,
                default=FALSE)
            private$..plot7 <- jmvcore::OptionBool$new(
                "plot7",
                plot7,
                default=FALSE)
            private$..plotRidge <- jmvcore::OptionBool$new(
                "plotRidge",
                plotRidge,
                default=FALSE)
            private$..trueCoef <- jmvcore::OptionString$new(
                "trueCoef",
                trueCoef,
                default="")

            self$.addOption(private$..run)
            self$.addOption(private$..dep)
            self$.addOption(private$..covs)
            self$.addOption(private$..factors)
            self$.addOption(private$..intercept)
            self$.addOption(private$..caseGLM)
            self$.addOption(private$..supportMethod)
            self$.addOption(private$..ridgeSignalSupport)
            self$.addOption(private$..ridgeLambdaMin)
            self$.addOption(private$..ridgeLambdaMax)
            self$.addOption(private$..ridgeLambdaN)
            self$.addOption(private$..M)
            self$.addOption(private$..J)
            self$.addOption(private$..weight)
            self$.addOption(private$..cvNfolds)
            self$.addOption(private$..errorMeasure)
            self$.addOption(private$..errorMeasureWhich)
            self$.addOption(private$..supportSignalVectorMin)
            self$.addOption(private$..supportSignalVectorMax)
            self$.addOption(private$..supportSignalVectorN)
            self$.addOption(private$..noiseSupportMethod)
            self$.addOption(private$..twostepsN)
            self$.addOption(private$..seed)
            self$.addOption(private$..OLS)
            self$.addOption(private$..NormEnt)
            self$.addOption(private$..bootstrap)
            self$.addOption(private$..bootB)
            self$.addOption(private$..bootMethod)
            self$.addOption(private$..bootCIMethod)
            self$.addOption(private$..bootConfLevel)
            self$.addOption(private$..method)
            self$.addOption(private$..plot1)
            self$.addOption(private$..plot2)
            self$.addOption(private$..plot3)
            self$.addOption(private$..plot4)
            self$.addOption(private$..plot5)
            self$.addOption(private$..plot6)
            self$.addOption(private$..plot7)
            self$.addOption(private$..plotRidge)
            self$.addOption(private$..trueCoef)
        }),
    active = list(
        run = function() private$..run$value,
        dep = function() private$..dep$value,
        covs = function() private$..covs$value,
        factors = function() private$..factors$value,
        intercept = function() private$..intercept$value,
        caseGLM = function() private$..caseGLM$value,
        supportMethod = function() private$..supportMethod$value,
        ridgeSignalSupport = function() private$..ridgeSignalSupport$value,
        ridgeLambdaMin = function() private$..ridgeLambdaMin$value,
        ridgeLambdaMax = function() private$..ridgeLambdaMax$value,
        ridgeLambdaN = function() private$..ridgeLambdaN$value,
        M = function() private$..M$value,
        J = function() private$..J$value,
        weight = function() private$..weight$value,
        cvNfolds = function() private$..cvNfolds$value,
        errorMeasure = function() private$..errorMeasure$value,
        errorMeasureWhich = function() private$..errorMeasureWhich$value,
        supportSignalVectorMin = function() private$..supportSignalVectorMin$value,
        supportSignalVectorMax = function() private$..supportSignalVectorMax$value,
        supportSignalVectorN = function() private$..supportSignalVectorN$value,
        noiseSupportMethod = function() private$..noiseSupportMethod$value,
        twostepsN = function() private$..twostepsN$value,
        seed = function() private$..seed$value,
        OLS = function() private$..OLS$value,
        NormEnt = function() private$..NormEnt$value,
        bootstrap = function() private$..bootstrap$value,
        bootB = function() private$..bootB$value,
        bootMethod = function() private$..bootMethod$value,
        bootCIMethod = function() private$..bootCIMethod$value,
        bootConfLevel = function() private$..bootConfLevel$value,
        method = function() private$..method$value,
        plot1 = function() private$..plot1$value,
        plot2 = function() private$..plot2$value,
        plot3 = function() private$..plot3$value,
        plot4 = function() private$..plot4$value,
        plot5 = function() private$..plot5$value,
        plot6 = function() private$..plot6$value,
        plot7 = function() private$..plot7$value,
        plotRidge = function() private$..plotRidge$value,
        trueCoef = function() private$..trueCoef$value),
    private = list(
        ..run = NA,
        ..dep = NA,
        ..covs = NA,
        ..factors = NA,
        ..intercept = NA,
        ..caseGLM = NA,
        ..supportMethod = NA,
        ..ridgeSignalSupport = NA,
        ..ridgeLambdaMin = NA,
        ..ridgeLambdaMax = NA,
        ..ridgeLambdaN = NA,
        ..M = NA,
        ..J = NA,
        ..weight = NA,
        ..cvNfolds = NA,
        ..errorMeasure = NA,
        ..errorMeasureWhich = NA,
        ..supportSignalVectorMin = NA,
        ..supportSignalVectorMax = NA,
        ..supportSignalVectorN = NA,
        ..noiseSupportMethod = NA,
        ..twostepsN = NA,
        ..seed = NA,
        ..OLS = NA,
        ..NormEnt = NA,
        ..bootstrap = NA,
        ..bootB = NA,
        ..bootMethod = NA,
        ..bootCIMethod = NA,
        ..bootConfLevel = NA,
        ..method = NA,
        ..plot1 = NA,
        ..plot2 = NA,
        ..plot3 = NA,
        ..plot4 = NA,
        ..plot5 = NA,
        ..plot6 = NA,
        ..plot7 = NA,
        ..plotRidge = NA,
        ..trueCoef = NA)
)

LMGCEResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "LMGCEResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        reference = function() private$.items[["reference"]],
        modelSummary = function() private$.items[["modelSummary"]],
        coefficients = function() private$.items[["coefficients"]],
        plot1 = function() private$.items[["plot1"]],
        plot2 = function() private$.items[["plot2"]],
        plot3 = function() private$.items[["plot3"]],
        plot4 = function() private$.items[["plot4"]],
        plot5 = function() private$.items[["plot5"]],
        plot6 = function() private$.items[["plot6"]],
        plot7 = function() private$.items[["plot7"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="GCE Linear Model",
                refs=list(
                    "GCEstim"))
            self$add(jmvcore::Html$new(
                options=options,
                name="text",
                title="Status"))
            self$add(jmvcore::Html$new(
                options=options,
                name="reference",
                title="GCEstim reference"))
            self$add(jmvcore::Table$new(
                options=options,
                name="modelSummary",
                title="Model Summary",
                columns=list(
                    list(
                        `name`="measure", 
                        `title`="Measure", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="coefficients",
                title="Coefficients",
                columns=list(
                    list(
                        `name`="term", 
                        `title`="Term", 
                        `type`="text"),
                    list(
                        `name`="estimate", 
                        `title`="Estimate", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ciLowerZ", 
                        `title`="CI Lower", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(bootstrap == 0)"),
                    list(
                        `name`="ciUpperZ", 
                        `title`="CI Upper", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(bootstrap == 0)"),
                    list(
                        `name`="ciLower", 
                        `title`="Bootstrap CI Lower", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(bootstrap)"),
                    list(
                        `name`="ciUpper", 
                        `title`="Bootstrap CI Upper", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(bootstrap)"),
                    list(
                        `name`="se", 
                        `title`="Std. Deviation", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(bootstrap == 0)"),
                    list(
                        `name`="z", 
                        `title`="z value", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(bootstrap == 0)"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(bootstrap == 0)"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Estimates and confidence intervals",
                renderFun=".plot1",
                visible="(plot1)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot2",
                title="Supports vs prediction error",
                renderFun=".plot2",
                visible="(plot2)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot3",
                title="Supports vs estimates",
                renderFun=".plot3",
                visible="(plot3)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot4",
                title="Supports vs normalized entropy",
                renderFun=".plot4",
                visible="(plot4)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot5",
                title="Supports vs precision error",
                renderFun=".plot5",
                visible="(plot5)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot6",
                title="GCE reestimation vs prediction error",
                renderFun=".plot6",
                visible="(plot6)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot7",
                title="GCE reestimation vs precision error",
                renderFun=".plot7",
                visible="(plot7)"))}))

LMGCEBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "LMGCEBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "GCEstimjmv",
                name = "LMGCE",
                version = c(1,0,0),
                options = options,
                results = LMGCEResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' GCE Linear Model
#'
#' 
#' @param run .
#' @param data .
#' @param dep .
#' @param covs .
#' @param factors .
#' @param intercept .
#' @param caseGLM .
#' @param supportMethod .
#' @param ridgeSignalSupport .
#' @param ridgeLambdaMin .
#' @param ridgeLambdaMax .
#' @param ridgeLambdaN .
#' @param M .
#' @param J .
#' @param weight .
#' @param cvNfolds .
#' @param errorMeasure .
#' @param errorMeasureWhich .
#' @param supportSignalVectorMin .
#' @param supportSignalVectorMax .
#' @param supportSignalVectorN .
#' @param noiseSupportMethod .
#' @param twostepsN .
#' @param seed .
#' @param OLS .
#' @param NormEnt .
#' @param bootstrap .
#' @param bootB .
#' @param bootMethod .
#' @param bootCIMethod .
#' @param bootConfLevel .
#' @param method .
#' @param plot1 .
#' @param plot2 .
#' @param plot3 .
#' @param plot4 .
#' @param plot5 .
#' @param plot6 .
#' @param plot7 .
#' @param plotRidge .
#' @param trueCoef .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$reference} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$modelSummary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$coefficients} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot2} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot3} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot4} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot5} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot6} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot7} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$modelSummary$asDF}
#'
#' \code{as.data.frame(results$modelSummary)}
#'
#' @export
LMGCE <- function(
    run = FALSE,
    data,
    dep,
    covs,
    factors,
    intercept = TRUE,
    caseGLM = "D",
    supportMethod = "standardized",
    ridgeSignalSupport = "symm",
    ridgeLambdaMin = 0.001,
    ridgeLambdaMax = 1000,
    ridgeLambdaN = 100,
    M = 3,
    J = 3,
    weight = 0.5,
    cvNfolds = 5,
    errorMeasure = "RMSE",
    errorMeasureWhich = "1se",
    supportSignalVectorMin = 0.3,
    supportSignalVectorMax = 20,
    supportSignalVectorN = 20,
    noiseSupportMethod = "sigma3",
    twostepsN = 1,
    seed = 230676,
    OLS = FALSE,
    NormEnt = FALSE,
    bootstrap = FALSE,
    bootB = 10,
    bootMethod = "residuals",
    bootCIMethod = "percentile",
    bootConfLevel = 0.95,
    method = "dual.BFGS",
    plot1 = TRUE,
    plot2 = TRUE,
    plot3 = TRUE,
    plot4 = FALSE,
    plot5 = FALSE,
    plot6 = FALSE,
    plot7 = FALSE,
    plotRidge = FALSE,
    trueCoef = "") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("LMGCE requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(covs)) covs <- jmvcore::resolveQuo(jmvcore::enquo(covs))
    if ( ! missing(factors)) factors <- jmvcore::resolveQuo(jmvcore::enquo(factors))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(covs), covs, NULL),
            `if`( ! missing(factors), factors, NULL))


    options <- LMGCEOptions$new(
        run = run,
        dep = dep,
        covs = covs,
        factors = factors,
        intercept = intercept,
        caseGLM = caseGLM,
        supportMethod = supportMethod,
        ridgeSignalSupport = ridgeSignalSupport,
        ridgeLambdaMin = ridgeLambdaMin,
        ridgeLambdaMax = ridgeLambdaMax,
        ridgeLambdaN = ridgeLambdaN,
        M = M,
        J = J,
        weight = weight,
        cvNfolds = cvNfolds,
        errorMeasure = errorMeasure,
        errorMeasureWhich = errorMeasureWhich,
        supportSignalVectorMin = supportSignalVectorMin,
        supportSignalVectorMax = supportSignalVectorMax,
        supportSignalVectorN = supportSignalVectorN,
        noiseSupportMethod = noiseSupportMethod,
        twostepsN = twostepsN,
        seed = seed,
        OLS = OLS,
        NormEnt = NormEnt,
        bootstrap = bootstrap,
        bootB = bootB,
        bootMethod = bootMethod,
        bootCIMethod = bootCIMethod,
        bootConfLevel = bootConfLevel,
        method = method,
        plot1 = plot1,
        plot2 = plot2,
        plot3 = plot3,
        plot4 = plot4,
        plot5 = plot5,
        plot6 = plot6,
        plot7 = plot7,
        plotRidge = plotRidge,
        trueCoef = trueCoef)

    analysis <- LMGCEClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

