
# This file is automatically generated, you probably don't want to edit this

WGCEOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "WGCEOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            run = FALSE,
            dep = NULL,
            covs = NULL,
            factors = NULL,
            intercept = TRUE,
            supportSignalLowers = "-10",
            supportSignalUppers = "10",
            M = 3,
            J = 3,
            weight = 0.5,
            supportNoise3sig = TRUE,
            supportNoiseMin = -10,
            supportNoiseMax = 10,
            method = "dual.BFGS",
            caseGLM = "D",
            bootConfLevel = 0.95,
            bootstrap = FALSE,
            bootB = 100,
            bootMethod = "residuals",
            bootCIMethod = "percentile",
            OLS = FALSE,
            seed = 230676,
            plot1 = TRUE, ...) {

            super$initialize(
                package="GCEstimjmv",
                name="WGCE",
                requiresData=TRUE,
                ...)

            private$..run <- jmvcore::OptionAction$new(
                "run",
                run)
            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs)
            private$..factors <- jmvcore::OptionVariables$new(
                "factors",
                factors)
            private$..intercept <- jmvcore::OptionBool$new(
                "intercept",
                intercept,
                default=TRUE)
            private$..supportSignalLowers <- jmvcore::OptionString$new(
                "supportSignalLowers",
                supportSignalLowers,
                default="-10")
            private$..supportSignalUppers <- jmvcore::OptionString$new(
                "supportSignalUppers",
                supportSignalUppers,
                default="10")
            private$..M <- jmvcore::OptionInteger$new(
                "M",
                M,
                default=3,
                min=3,
                max=99)
            private$..J <- jmvcore::OptionInteger$new(
                "J",
                J,
                default=3,
                min=3,
                max=99)
            private$..weight <- jmvcore::OptionNumber$new(
                "weight",
                weight,
                default=0.5,
                min=0,
                max=1)
            private$..supportNoise3sig <- jmvcore::OptionBool$new(
                "supportNoise3sig",
                supportNoise3sig,
                default=TRUE)
            private$..supportNoiseMin <- jmvcore::OptionNumber$new(
                "supportNoiseMin",
                supportNoiseMin,
                default=-10)
            private$..supportNoiseMax <- jmvcore::OptionNumber$new(
                "supportNoiseMax",
                supportNoiseMax,
                default=10)
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "dual.BFGS",
                    "dual.lbfgsb3c",
                    "dual.L-BFGS-B",
                    "dual.lbfgs",
                    "dual.CG",
                    "dual.Rcgmin",
                    "dual.bobyqa",
                    "dual.newuoa",
                    "dual.nlminb",
                    "dual.nlm",
                    "primal.solnl",
                    "primal.solnp"),
                default="dual.BFGS")
            private$..caseGLM <- jmvcore::OptionList$new(
                "caseGLM",
                caseGLM,
                options=list(
                    "D",
                    "M",
                    "NM"),
                default="D")
            private$..bootConfLevel <- jmvcore::OptionNumber$new(
                "bootConfLevel",
                bootConfLevel,
                default=0.95,
                min=0.5,
                max=0.99)
            private$..bootstrap <- jmvcore::OptionBool$new(
                "bootstrap",
                bootstrap,
                default=FALSE)
            private$..bootB <- jmvcore::OptionInteger$new(
                "bootB",
                bootB,
                default=100,
                min=10)
            private$..bootMethod <- jmvcore::OptionList$new(
                "bootMethod",
                bootMethod,
                options=list(
                    "residuals",
                    "cases",
                    "wild"),
                default="residuals")
            private$..bootCIMethod <- jmvcore::OptionList$new(
                "bootCIMethod",
                bootCIMethod,
                options=list(
                    "percentile",
                    "basic"),
                default="percentile")
            private$..OLS <- jmvcore::OptionBool$new(
                "OLS",
                OLS,
                default=FALSE)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                default=230676,
                min=1)
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=TRUE)
            private$..saveFitted <- jmvcore::OptionOutput$new(
                "saveFitted")
            private$..saveResiduals <- jmvcore::OptionOutput$new(
                "saveResiduals")
            private$..saveW <- jmvcore::OptionOutput$new(
                "saveW")

            self$.addOption(private$..run)
            self$.addOption(private$..dep)
            self$.addOption(private$..covs)
            self$.addOption(private$..factors)
            self$.addOption(private$..intercept)
            self$.addOption(private$..supportSignalLowers)
            self$.addOption(private$..supportSignalUppers)
            self$.addOption(private$..M)
            self$.addOption(private$..J)
            self$.addOption(private$..weight)
            self$.addOption(private$..supportNoise3sig)
            self$.addOption(private$..supportNoiseMin)
            self$.addOption(private$..supportNoiseMax)
            self$.addOption(private$..method)
            self$.addOption(private$..caseGLM)
            self$.addOption(private$..bootConfLevel)
            self$.addOption(private$..bootstrap)
            self$.addOption(private$..bootB)
            self$.addOption(private$..bootMethod)
            self$.addOption(private$..bootCIMethod)
            self$.addOption(private$..OLS)
            self$.addOption(private$..seed)
            self$.addOption(private$..plot1)
            self$.addOption(private$..saveFitted)
            self$.addOption(private$..saveResiduals)
            self$.addOption(private$..saveW)
        }),
    active = list(
        run = function() private$..run$value,
        dep = function() private$..dep$value,
        covs = function() private$..covs$value,
        factors = function() private$..factors$value,
        intercept = function() private$..intercept$value,
        supportSignalLowers = function() private$..supportSignalLowers$value,
        supportSignalUppers = function() private$..supportSignalUppers$value,
        M = function() private$..M$value,
        J = function() private$..J$value,
        weight = function() private$..weight$value,
        supportNoise3sig = function() private$..supportNoise3sig$value,
        supportNoiseMin = function() private$..supportNoiseMin$value,
        supportNoiseMax = function() private$..supportNoiseMax$value,
        method = function() private$..method$value,
        caseGLM = function() private$..caseGLM$value,
        bootConfLevel = function() private$..bootConfLevel$value,
        bootstrap = function() private$..bootstrap$value,
        bootB = function() private$..bootB$value,
        bootMethod = function() private$..bootMethod$value,
        bootCIMethod = function() private$..bootCIMethod$value,
        OLS = function() private$..OLS$value,
        seed = function() private$..seed$value,
        plot1 = function() private$..plot1$value,
        saveFitted = function() private$..saveFitted$value,
        saveResiduals = function() private$..saveResiduals$value,
        saveW = function() private$..saveW$value),
    private = list(
        ..run = NA,
        ..dep = NA,
        ..covs = NA,
        ..factors = NA,
        ..intercept = NA,
        ..supportSignalLowers = NA,
        ..supportSignalUppers = NA,
        ..M = NA,
        ..J = NA,
        ..weight = NA,
        ..supportNoise3sig = NA,
        ..supportNoiseMin = NA,
        ..supportNoiseMax = NA,
        ..method = NA,
        ..caseGLM = NA,
        ..bootConfLevel = NA,
        ..bootstrap = NA,
        ..bootB = NA,
        ..bootMethod = NA,
        ..bootCIMethod = NA,
        ..OLS = NA,
        ..seed = NA,
        ..plot1 = NA,
        ..saveFitted = NA,
        ..saveResiduals = NA,
        ..saveW = NA)
)

WGCEResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "WGCEResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        reference = function() private$.items[["reference"]],
        modelSummary = function() private$.items[["modelSummary"]],
        signalSupports = function() private$.items[["signalSupports"]],
        coefficients = function() private$.items[["coefficients"]],
        plot1 = function() private$.items[["plot1"]],
        saveFitted = function() private$.items[["saveFitted"]],
        saveResiduals = function() private$.items[["saveResiduals"]],
        saveW = function() private$.items[["saveW"]],
        signalProbabilities = function() private$.items[["signalProbabilities"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="W-GCE Linear Model",
                refs=list(
                    "GCEstim"))
            self$add(jmvcore::Html$new(
                options=options,
                name="text",
                title="Status"))
            self$add(jmvcore::Html$new(
                options=options,
                name="reference",
                title="GCEstim reference"))
            self$add(jmvcore::Table$new(
                options=options,
                name="modelSummary",
                title="Model Summary",
                columns=list(
                    list(
                        `name`="measure", 
                        `title`="Measure", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="signalSupports",
                title="Signal Supports",
                columns=list(
                    list(
                        `name`="term", 
                        `title`="Coefficient", 
                        `type`="text"),
                    list(
                        `name`="lower", 
                        `title`="Lower limit", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="upper", 
                        `title`="Upper limit", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="coefficients",
                title="Coefficients",
                columns=list(
                    list(
                        `name`="term", 
                        `title`="Term", 
                        `type`="text"),
                    list(
                        `name`="estimate", 
                        `title`="Estimate", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ciLowerZ", 
                        `title`="CI Lower", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(bootstrap == 0)"),
                    list(
                        `name`="ciUpperZ", 
                        `title`="CI Upper", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(bootstrap == 0)"),
                    list(
                        `name`="ciLower", 
                        `title`="Bootstrap CI Lower", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(bootstrap)"),
                    list(
                        `name`="ciUpper", 
                        `title`="Bootstrap CI Upper", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(bootstrap)"),
                    list(
                        `name`="se", 
                        `title`="Std. Deviation", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(bootstrap == 0)"),
                    list(
                        `name`="z", 
                        `title`="z value", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(bootstrap == 0)"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(bootstrap == 0)"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Estimates and confidence intervals",
                renderFun=".plot1",
                visible="(plot1)"))
            self$add(jmvcore::Output$new(
                options=options,
                name="saveFitted",
                title="Fitted values",
                varTitle="WGCE fitted",
                varDescription="W-GCE fitted value for each complete observation",
                measureType="continuous"))
            self$add(jmvcore::Output$new(
                options=options,
                name="saveResiduals",
                title="Residuals",
                varTitle="WGCE residual",
                varDescription="W-GCE residual for each complete observation",
                measureType="continuous"))
            self$add(jmvcore::Output$new(
                options=options,
                name="saveW",
                title="Estimated noise support probabilities (w)",
                varTitle="WGCE w_$key",
                varDescription="W-GCE noise probability at support point $key",
                measureType="continuous",
                items="(J)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="signalProbabilities",
                title="Estimated signal support probabilities (p)",
                columns=list(
                    list(
                        `name`="term", 
                        `title`="Coefficient", 
                        `type`="text"))))}))

WGCEBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "WGCEBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "GCEstimjmv",
                name = "WGCE",
                version = c(1,0,0),
                options = options,
                results = WGCEResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' W-GCE Linear Model
#'
#' 
#' @param run .
#' @param data .
#' @param dep .
#' @param covs .
#' @param factors .
#' @param intercept .
#' @param supportSignalLowers .
#' @param supportSignalUppers .
#' @param M .
#' @param J .
#' @param weight .
#' @param supportNoise3sig .
#' @param supportNoiseMin .
#' @param supportNoiseMax .
#' @param method .
#' @param caseGLM .
#' @param bootConfLevel .
#' @param bootstrap .
#' @param bootB .
#' @param bootMethod .
#' @param bootCIMethod .
#' @param OLS .
#' @param seed .
#' @param plot1 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$reference} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$modelSummary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$signalSupports} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$coefficients} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$saveFitted} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$saveResiduals} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$saveW} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$signalProbabilities} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$modelSummary$asDF}
#'
#' \code{as.data.frame(results$modelSummary)}
#'
#' @export
WGCE <- function(
    run = FALSE,
    data,
    dep,
    covs,
    factors,
    intercept = TRUE,
    supportSignalLowers = "-10",
    supportSignalUppers = "10",
    M = 3,
    J = 3,
    weight = 0.5,
    supportNoise3sig = TRUE,
    supportNoiseMin = -10,
    supportNoiseMax = 10,
    method = "dual.BFGS",
    caseGLM = "D",
    bootConfLevel = 0.95,
    bootstrap = FALSE,
    bootB = 100,
    bootMethod = "residuals",
    bootCIMethod = "percentile",
    OLS = FALSE,
    seed = 230676,
    plot1 = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("WGCE requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(covs)) covs <- jmvcore::resolveQuo(jmvcore::enquo(covs))
    if ( ! missing(factors)) factors <- jmvcore::resolveQuo(jmvcore::enquo(factors))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(covs), covs, NULL),
            `if`( ! missing(factors), factors, NULL))


    options <- WGCEOptions$new(
        run = run,
        dep = dep,
        covs = covs,
        factors = factors,
        intercept = intercept,
        supportSignalLowers = supportSignalLowers,
        supportSignalUppers = supportSignalUppers,
        M = M,
        J = J,
        weight = weight,
        supportNoise3sig = supportNoise3sig,
        supportNoiseMin = supportNoiseMin,
        supportNoiseMax = supportNoiseMax,
        method = method,
        caseGLM = caseGLM,
        bootConfLevel = bootConfLevel,
        bootstrap = bootstrap,
        bootB = bootB,
        bootMethod = bootMethod,
        bootCIMethod = bootCIMethod,
        OLS = OLS,
        seed = seed,
        plot1 = plot1)

    analysis <- WGCEClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

